/**
 * Word-level sign vocabulary.
 *
 * GENERATED by tools/gen-dictionary.cjs — edit the table there, not this file.
 *
 * Each entry maps one or more English words onto a single sign. A sign may be
 * shown as a video or, where no video has been licensed yet, a still image.
 * Words with no entry here are fingerspelled instead; see src/lib/sign-lookup.ts.
 *
 * ## Licensing
 *
 * Every entry carries its own licence, and `assertCommercialUse()` below
 * refuses to load the module if any entry is not cleared for commercial use.
 * This site runs AdSense, which makes it commercial use, and the major open ASL
 * video corpora do not permit that:
 *
 *   - WLASL is C-UDA, "academic and computational use only".
 *   - ASL-LEX prohibits commercial use expressly.
 *   - ASL Citizen (Microsoft) is non-commercial by default, but a commercial
 *     licence can be negotiated — ASL_Citizen@microsoft.com.
 *   - Wikimedia Commons CC BY-SA / public-domain clips are usable now, with
 *     attribution recorded in the `license` field.
 *
 * The assertion is what makes that a structural guarantee rather than a note in
 * a README that someone eventually stops reading.
 */

export type SignLicense = {
  /** Human-readable licence name, e.g. "CC BY-SA 4.0". */
  name: string;
  /** Link to the licence or the source page. */
  url?: string;
  /** Attribution line to display, where the licence requires one. */
  attribution?: string;
  /** Cleared for use on an ad-funded site. */
  commercial: boolean;
};

export type SignEntry = {
  /** Canonical ASL gloss, uppercase; hyphens join a multi-word sign. */
  gloss: string;
  /** English forms resolving to this sign. The first is used as the label. */
  words: string[];
  /** Video of the sign, once one has been licensed. */
  video?: { src: string; poster?: string };
  /** Still image — what the site has today. */
  image?: string;
  /** Intrinsic pixel size of `image`, used to reserve layout space. */
  width?: number;
  height?: number;
  license: SignLicense;
};

export const signDictionary: SignEntry[] = [
  {gloss:"HELLO",words:["hello"],image:"/sign-language-words/hello-in-sign-langauge.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"HI",words:["hi","hey"],image:"/sign-language-words/hi-in-american-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"GOODBYE",words:["goodbye","bye","good bye"],image:"/assets/images/goodbye-in-sign-language.webp",width:461,height:473,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"GOOD-MORNING",words:["good morning"],image:"/assets/images/good-morning-in-sign-language.webp",width:463,height:507,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"GOOD-NIGHT",words:["good night","goodnight"],image:"/assets/images/good-night-in-sign-language.webp",width:478,height:467,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"HOW-ARE-YOU",words:["how are you"],image:"/sign-language-words/how-are-you-in-asl.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"HAVE-GOOD-DAY",words:["have a good day"],image:"/sign-language-words/have-a-good-day-in-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"HAPPY-BIRTHDAY",words:["happy birthday"],image:"/sign-language-words/happy-birthday-in-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"PLEASE",words:["please"],image:"/sign-language-words/please-in-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"THANK-YOU",words:["thank you","thanks","thankyou"],image:"/assets/images/thank-you-in-sign-language.webp",width:487,height:489,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"YOURE-WELCOME",words:["you're welcome","you are welcome","youre welcome"],image:"/sign-language-words/youe-welcome-in-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"SORRY",words:["sorry","apologize"],image:"/sign-language-words/sorry-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"EXCUSE-ME",words:["excuse me"],image:"/assets/images/excuse-me-in-sign-language.webp",width:469,height:480,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"YES",words:["yes","yeah","yep"],image:"/assets/images/yes-in-sign-language.webp",width:476,height:494,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"NO",words:["no","nope"],image:"/sign-language-words/no-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"MORE",words:["more"],image:"/sign-language-words/more-in-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"ALL-DONE",words:["all done","finished","done"],image:"/sign-language-words/all-done-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"WAIT",words:["wait"],image:"/sign-language-words/wait-in-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"STOP",words:["stop"],image:"/assets/images/stop-in-sign-language.webp",width:474,height:513,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"GO",words:["go"],image:"/assets/images/go-in-sign-language.webp",width:486,height:488,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"HELP",words:["help"],image:"/sign-language-words/help-in-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"WHAT",words:["what"],image:"/sign-language-words/what-in-asl.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"WHEN",words:["when"],image:"/assets/images/when-in-sign-language.webp",width:502,height:483,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"WHERE",words:["where"],image:"/assets/images/where-in-sign-language.webp",width:486,height:489,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"WHO",words:["who"],image:"/assets/images/who-in-sign-language.webp",width:505,height:516,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"MOM",words:["mom","mother","mum","mommy","mama"],image:"/sign-language-words/mom-in-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"DAD",words:["dad","father","daddy","papa"],image:"/sign-language-words/dad-in-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"FAMILY",words:["family"],image:"/sign-language-words/family-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"FRIEND",words:["friend"],image:"/assets/images/friend-in-sign-language.webp",width:482,height:493,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"I-LOVE-YOU",words:["i love you"],image:"/sign-language-words/i-love-you-in-sign-language.webp",width:540,height:540,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"LOVE",words:["love"],image:"/assets/images/love-in-sign-language.webp",width:523,height:521,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"HAPPY",words:["happy","glad"],image:"/assets/images/happy-in-sign-language.webp",width:490,height:486,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"SAD",words:["sad"],image:"/assets/images/sad-in-sign-language.webp",width:465,height:477,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"HOT",words:["hot"],image:"/assets/images/hot-in-sign-language.webp",width:471,height:485,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"COLD",words:["cold"],image:"/assets/images/cold-in-sign-language.webp",width:483,height:492,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"EAT",words:["eat","food"],image:"/assets/images/eat-in-sign-language.webp",width:505,height:522,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"DRINK",words:["drink"],image:"/assets/images/drink-in-sign-language.webp",width:470,height:495,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"BATHROOM",words:["bathroom","toilet","restroom"],image:"/assets/images/bathroom-in-sign-language.webp",width:498,height:507,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"HOME",words:["home"],image:"/assets/images/home-in-sign-language.webp",width:515,height:512,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"SCHOOL",words:["school"],image:"/assets/images/school-in-sign-language.webp",width:512,height:515,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"WORK",words:["work","job"],image:"/assets/images/work-in-sign-language.webp",width:521,height:520,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"CAT",words:["cat"],image:"/assets/images/cat-in-sign-language.webp",width:487,height:490,license:{"name":"SLTranslator (own work)","commercial":true}},
  {gloss:"DOG",words:["dog"],image:"/assets/images/dog-in-sign-language.webp",width:505,height:523,license:{"name":"SLTranslator (own work)","commercial":true}},
];

/**
 * Refuses to load if any entry is not cleared for commercial use. Runs at
 * module load, so `next build` fails rather than shipping the asset.
 */
function assertCommercialUse(entries: SignEntry[]): void {
  const bad = entries.filter((e) => !e.license.commercial);
  if (bad.length > 0) {
    throw new Error(
      `sign-dictionary: ${bad.length} entr${bad.length === 1 ? "y is" : "ies are"} not cleared ` +
        `for commercial use and this site runs ads: ${bad.map((e) => e.gloss).join(", ")}. ` +
        `Remove them or obtain a commercial licence.`,
    );
  }
}

assertCommercialUse(signDictionary);
